server:
  port: 8084
  forward-headers-strategy: native

spring:
  application:
    name: admin-service
  datasource:
    url: ${ADMIN_DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  lifecycle:
    timeout-per-shutdown-phase: 30s
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: false

spring.cloud:
  openfeign:
    httpclient:
      hc5:
        enabled: true
    circuitbreaker:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 5
        sliding-window-type: COUNT_BASED
        ignore-exceptions:
          - feign.FeignException.NotFound
          - feign.FeignException.BadRequest
          - feign.FeignException.Conflict
          - feign.FeignException.UnprocessableEntity
    instances:
      AUTH-SERVICE:
        base-config: default
      POLICY-SERVICE:
        base-config: default
      CLAIMS-SERVICE:
        base-config: default
      ADMIN-SERVICE:
        base-config: default

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: b3
  observations:
    key-values:
      application: ${spring.application.name}
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans