server:
  port: 8085

spring:
  application:
    name: notification-service
  
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  lifecycle:
    timeout-per-shutdown-phase: 30s

eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

logging:
  level:
    com.dev.notification: DEBUG
    org.springframework.amqp: DEBUG

spring.cloud:
  openfeign:
    circuitbreaker:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 5
        sliding-window-type: COUNT_BASED
    instances:
      auth-service:
        base-config: default
      notification-service:
        base-config: default

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: b3
  observations:
    key-values:
      application: ${spring.application.name}
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
